{"name": "Проверка логина курьера с неверным паролем", "status": "passed", "description": "Логиним курьера с существующим логином с неправильным паролемпроверяем, что в ответе получаем статус 404 и сообщение Учетная запись не найдена", "steps": [{"name": "вызываем метод make_request для ручки логина курьера", "status": "passed", "steps": [{"name": "вызываем нужный метод requests по переданным параметрам", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/courier/login'"}, {"name": "type", "value": "'post'"}, {"name": "payload", "value": "{'login': 'rtqmguxexf', 'password': '12345'}"}], "start": 1698861780652, "stop": 1698861780734}], "parameters": [{"name": "payload", "value": "{'login': 'rtqmguxexf', 'password': '12345'}"}], "start": 1698861780652, "stop": 1698861780734}], "start": 1698861780652, "stop": 1698861780735, "uuid": "4083b49e-35c9-4469-9151-e619c0891de7", "historyId": "71149c8676f4bdc45be7d6e53015ca63", "testCaseId": "71149c8676f4bdc45be7d6e53015ca63", "fullName": "tests.test_login_courier#test_login_courier_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "TCCIT0020"}, {"name": "thread", "value": "55097-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}